eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8000

spring:
  application:
      name: auth-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 856132508450-eap1r2defedlscc26mkoiqj21v0dshh4.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 917355857043361
            client-secret: 1322284ce9097c89e9597e807f5fbb54
  datasource:
    url: jdbc:postgresql://localhost:5432/cinemazone
    username: admin
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    #springdoc:
#  packages-to-scan:
#    com.trvankiet.app
#  api-docs:
#    path: /v3/api-docs/group-service
    
#management:
#  tracing:
#    sampling:
#      probability: 1.0
