jwt:
  private-key-path: classpath:keys/private.pem
  public-key-path: classpath:keys/public.pem

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

server:
  port: 8300

spring:
  application:
    name: auth-service
  data:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinemazone
    username: admin
    password: cmwJX01ECDDJkwxNvIPDLfUf9hvvZhgo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  packages-to-scan:
    com.trvankiet.app
  api-docs:
    path: /v3/api-docs/group-service
    
#management:
#  tracing:
#    sampling:
#      probability: 1.0
