jwt:
  private-key-path: classpath:keys/private.pem
  public-key-path: classpath:keys/public.pem

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8000
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 5s
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      delivery-timeout-ms: 120000
      enable-idempotence: true
      linger-ms: 10
      batch-size: 32768
      properties:
        max.in.flight.requests.per.connection: 5
        compression.type: lz4
  application:
    name: auth-service
    security:
      jwt:
        expiration: 86400000 # 24 giờ (tính bằng mili giây)
        refresh-token:
          expiration: 604800000 # 7 ngày (tính bằng mili giây)
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    stream:
      default:
        group: ${spring.application.name}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
