spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SERVICE_MAIL_USERNAME}
    password: ${EMAIL_SERVICE_MAIL_PASSWORD}
    test-connection: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.debug: false               # true để debug SMTP
  application:
    name: email-service
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME:admin}:${MONGO_DB_PASSWORD:admin123}@restora.xde1bim.mongodb.net/email_service?retryWrites=true&w=majority
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*' # Allow all packages to be deserialized
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 50
    listener:
      ack-mode: MANUAL             # tự commit sau khi gửi email OK
      concurrency: 3               # scale ngang theo partitions

server:
  port: 8702
# Google reCAPTCHA
google:
  recaptcha:
    secret-key: ${CAPTCHA_SECRET_KEY}
    site-key: ${CAPTCHA_SITE_KEY}
