server:
  port: 8702
spring:
  application:
    name: email-service
  cloud:
    stream:
      default:
        group: ${spring.application.name}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SERVICE_MAIL_USERNAME}
    password: ${EMAIL_SERVICE_MAIL_PASSWORD}
    test-connection: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000
      mail.smtp.ssl.trust: smtp.gmail.com
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 5s
  kafka:
    bootstrap-servers: localhost:9092


