spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SERVICE_MAIL_USERNAME:ngoquanghuy0310@gmail.com}
    password: ${EMAIL_SERVICE_MAIL_PASSWORD:qmpiiudifabgpyop}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: email-service
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME:admin}:${MONGO_DB_PASSWORD:admin123}@restora.xde1bim.mongodb.net/email_service?retryWrites=true&w=majority
  cloud:
    function:
      definition: emailSendRequestConsumer
    stream:
      bindings:
        emailSendRequestConsumer-in-0:
          destination: ops.email.send.request.v1
          group: email-service
          producer:
            required-groups: email-service
            configuration:
              acks: 1
              retries: 3
              batch-size: 16384
              linger-ms: 10
              max-block-ms: 60000
              compression-type: gzip
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
        bindings:
          emailSendRequestConsumer-in-0:
            consumer:
              enableDlq: true
              dlqName: ops.email.send.request.DLQ.v1
              ackMode: RECORD
              maxAttempts: 5
              backOffInitialInterval: 2000
              backOffMultiplier: 2.0
              backOffMaxInterval: 30000
server:
  port: 8702
# Google reCAPTCHA
google:
  recaptcha:
    secret-key: ${CAPTCHA_SECRET_KEY}
    site-key: ${CAPTCHA_SITE_KEY}
