spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SERVICE_MAIL_USERNAME:ngoquanghuy0310@gmail.com}
    password: ${EMAIL_SERVICE_MAIL_PASSWORD:qmpiiudifabgpyop}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: email-service
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME:admin}:${MONGO_DB_PASSWORD:admin123}@restora.xde1bim.mongodb.net/email_service?retryWrites=true&w=majority
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 50
    listener:
      ack-mode: MANUAL             # tự commit sau khi gửi email OK
      concurrency: 3               # scale ngang theo partitions

server:
  port: 8702
# Google reCAPTCHA
google:
  recaptcha:
    secret-key: ${CAPTCHA_SECRET_KEY}
    site-key: ${CAPTCHA_SITE_KEY}
