eureka:
  instance:
    hostname: media-service
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}


server:
  port: 8800

spring:
  application:
    name: media-service
  cloud:
    stream:
      default:
        group: ${spring.application.name}
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME:admin}:${MONGO_DB_PASSWORD:admin123}@restora.xde1bim.mongodb.net/media_service?retryWrites=true&w=majority
  kafka:
    bootstrap-servers: localhost:9092

# AWS Config
aws:
  region: "ap-southeast-1"
  s3:
    bucket-name: "novaplay-media-storage"
    presigned-url-duration-minutes: 10
  sqs:
    queue-name: "s3-events-queue"

aws.accessKeyId: ${YOUR_ACCESS_KEY}
aws.secretKey: ${YOUR_SECRET_KEY}

kafka-topics:
  media-ready: "media.ready.topic"

job:
  cleanup:
    fixed-rate-ms: 3600000
    pending-older-than-hours: 1
    fail-older-than-hours: 24

cdn:
  base-url: https://novaplay-media-storage.s3.ap-southeast-1.amazonaws.com

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html