eureka:
  instance:
    hostname: media_service
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 8800

spring:
  application:
    name: media_service
  cloud:
    stream:
      default:
        group: ${spring.application.name}
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME:admin}:${MONGO_DB_PASSWORD:admin123}@restora.xde1bim.mongodb.net/user_service?retryWrites=true&w=majority
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      delivery-timeout-ms: 120000
      enable-idempotence: true
      linger-ms: 10
      batch-size: 32768
      properties:
        max.in.flight.requests.per.connection: 5
        compression.type: lz4

# AWS Config
aws:
  region: "ap-southeast-1"
  s3:
    bucket-name: "novaplay-media-storage"
    presigned-url-duration-minutes: 10
  sqs:
    queue-name: "s3-events-queue"

aws.accessKeyId: ${YOUR_ACCESS_KEY}
aws.secretKey: ${YOUR_SECRET_KEY}

kafka-topics:
  media-ready: "media.ready.topic"

job:
  cleanup:
    fixed-rate-ms: 3600000
    pending-older-than-hours: 1
    fail-older-than-hours: 24

cdn:
  base-url: https://cdn.novaplay.com