eureka:
  instance:
    hostname: notification_service
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb+srv://admin:admin123@restora.xde1bim.mongodb.net/email-service?retryWrites=true&w=majority
  cloud:
    function:
      definition: notificationPushRequestConsumer
    stream:
      bindings:
        notificationPushRequestConsumer-in-0:
          destination: ops.notification.push.request.v1
          group: notification-service
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
        bindings:
          notificationPushRequestConsumer-in-0:
            consumer:
              enableDlq: true
              dlqName: ops.notification.push.request.DLQ.v1
              ackMode: RECORD
              maxAttempts: 4
              backOffInitialInterval: 1000
              backOffMultiplier: 2.0
              backOffMaxInterval: 20000
server:
  port: 8900
