eureka:
  instance:
    hostname: user-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8700

spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Mở các endpoint của Actuator, đặc biệt là bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: "*" # Mở tất cả endpoint, trong thực tế nên chọn lọc

app:
  message: "Ngo Diep Quang Huy"
