eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8000

spring:
  application:
    name: user-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB